name: CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: include node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install s3cmd
        run: pip install https://github.com/s3tools/s3cmd/archive/master.zip && echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc

      - name: build dependencies
        run: make dependencies_container

      - name: deploy to s3
        run: make deploy-prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_REGION: ca-central-1
  lighthouse-check:
    if: ${{false}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Lighthouse-check
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with: 
          outputDirectory: /tmp/artifacts
          prCommentSaveOld: true 
          fooApiToken: ${{secrets.LIGHTHOUSE_FOO_API_TOKEN}}
          urls: ''
          tag: ${{ github.event.head_commit.message }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minPerformanceScore: '50'
